apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

# Patch replica count without touching/duplicating the base Deployment manifest
replicas:
  - name: user-service-demo
    count: 1

# Patch the image tag the same way
images:
  - name: weather-alert/user-service
    newTag: latest

commonLabels:
  env: dev
