apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-demo
  namespace: weather-alert
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service-demo
  template:
    metadata:
      labels:
        app: user-service-demo
    spec:
      containers:
        - name: user-service
          image: weather-alert/user-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8001
          env:
            - name: PORT
              value: "8001"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DB_PASSWORD
          envFrom:
            - configMapRef:
                name: app-config
          readinessProbe:
            httpGet:
              path: /health
              port: 8001
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 128Mi
